converter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('converter/', include('currencyConverter.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

currencyConverter/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='home'),
	path('cv-admin/', views.AdminView, name='admin'),
	path('cv-admin/addCurrency/', views.addCurrency, name='addCurrency'),
	path('cv-admin/update/<country_id>/', views.update, name='update'),
	path("login/", views.Connexion, name='login'),
	path("logout/", views.disconnect, name='logout'),
	path("register/", views.Register.as_view(), name='register'),
	path('about/', views.about, name='about'),
	path('contact/', views.contact, name='contact'),

]

currencyConverter/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profil(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	phone = models.IntegerField()

class Country(models.Model):
	name = models.CharField(max_length=20)
	currency = models.CharField(max_length=20)
	usd_value = models.CharField(max_length=20)

	def __str__(self):
		return f"{self.name}(1{self.currency}={self.usd_value}$)"

class TransactionPercent(models.Model):
	trans_percent = models.FloatField()

	def __str__(self):
		return f"Le taux de transaction : {self.trans_percent}"

currencyConverter/forms.py
from .models import *
from django import forms

def getValue(str_value):
	if('/' in str_value):
		splited_string = str_value.split('/')
		return float(splited_string[0])/float(splited_string[1])
	else:
		return float(str_value)

	

class ConnexionForm(forms.Form):
	username = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'placeholder':'Username ',
				'class':'form-control'
				}
			)
		)
	password = forms.CharField(
		widget=forms.PasswordInput(
			attrs={
				'placeholder':'Password ',
				 'type':'password',
				 'class':'form-control'
				 }
			)
		)

class RegisterForm(forms.Form):
	username = forms.CharField( widget=forms.TextInput(
		attrs={'placeholder':'your phone number','class':'form-control'}),
		label='Phone number')
	firstname = forms.CharField( widget=forms.TextInput(
		attrs={'placeholder':'Firstname ','class':'form-control'}),
		label='Firstname')
	lastname = forms.CharField( widget=forms.TextInput(
		attrs={'placeholder':'Lastname ','class':'form-control'}),
		label='Lastname')
	password = forms.CharField( widget=forms.PasswordInput(
		attrs={'placeholder':'Password ','class':'form-control'}),
		label='Password')
	password2 = forms.CharField( widget=forms.PasswordInput(
		attrs={'placeholder':'Confirm password ','class':'form-control'}),
		label='Confirm password')

class CountryForm(forms.ModelForm):

	name = forms.CharField( widget=forms.TextInput(
		attrs={'placeholder':'Country name','class':'form-control'}),
		label='Country name'
		)
	currency = forms.CharField( widget=forms.TextInput(
		attrs={'placeholder':'Currency','class':'form-control'}),
		label='Country Code'
		)
	usd_value = forms.CharField(widget=forms.TextInput(
			attrs={'placeholder':'Country currency usd value','class':'form-control'}),
		label='USD Value'
		)

	class Meta:
		model = Country
		fields = '__all__'

class ConversionForm(forms.Form):
	country_from = forms.ModelChoiceField(
        widget = forms.Select(
            attrs = {'placeholder': 'Country From', 'class': 'form-control'}),
        label = 'Country From',
        queryset = Country.objects.all())

	country_to = forms.ModelChoiceField(
        widget = forms.Select(
            attrs = {'placeholder': 'Country To', 'class': 'form-control'}),
        label = 'Country To',
        queryset = Country.objects.all())

	amount = forms.FloatField(widget=forms.NumberInput(
			attrs={'placeholder':'Amount ','class':'form-control'}),
		label='Amount')

	trans_percent = TransactionPercent.objects.get(id=1)

	def __init__(self, *args, **kwargs):
		super(ConversionForm, self).__init__(*args, **kwargs)
		countries = Country.objects.all()
		countries = [(getValue(i.usd_value), i.name) for i in countries]
		self.fields['country_from'] = forms.ChoiceField(
	        widget = forms.Select(attrs = {'class': 'form-control'}),
	        label = 'Country From', choices = countries)
		self.fields['country_to'] = forms.ChoiceField(
	        widget = forms.Select(attrs = {'class': 'form-control'}),
	        label = 'Country To', choices = countries)


class ContactForm(forms.Form):
	subject = forms.CharField(
        widget = forms.TextInput(
            attrs = {'placeholder': 'Subject', 
                    'class': 'form-control',
                    }),
        label = 'Subject',
        )

	message = forms.CharField(
        widget = forms.Textarea(
            attrs = {'placeholder': 'Your Message', 
                    'class': 'form-control',
                    }),
        label = 'Message'
        )

	from_ = forms.EmailField(widget=forms.EmailInput(
			attrs={'placeholder':'Your Email ','class':'form-control'}),
		label='Amount',
		required=True)

currencyConverter/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate 
from django.views import View
from .models import *
from .forms import *
from django.contrib import messages
from django.core.mail import send_mail



def index(request):
	template_name='index.html'
	form = ConversionForm(request.POST)
	return render(request, template_name, locals())

@login_required(login_url=('login'))
def AdminView(request):
	template = 'admin.html'
	countries = Country.objects.all()
	if 'addCurrency' in request.POST:
		return redirect('addCurrency')

	return render(request, template, locals())

@login_required(login_url=('login'))
def addCurrency(request):
	template = 'forms.html'
	form = CountryForm(request.POST or None, request.FILES)
	if(request.method =="POST"):
		if(form.is_valid()):
			form.save()
			return redirect('admin')
	form = CountryForm()
	return render(request, template, locals())

def disconnect(request):
	logout(request)
	return redirect("home")


def Connexion(request):
	template_name = 'forms.html'
	connexion_form = ConnexionForm(request.POST)
	if connexion_form.is_valid():
		username = connexion_form.cleaned_data['username']
		password = connexion_form.cleaned_data['password']
		user = authenticate(username=username, password=password)
		if user:  # Si l'objet renvoyé n'est pas None
			login(request, user)
			messages.success(request, "You're now connected!")
			return redirect('admin')
		else:
			messages.error(request, "logins incorrect!")
	connexion_form = ConnexionForm()
	return render(request, template_name, locals())

class Register(View):
	template_name = 'forms.html'

	def post(self, request, *args, **kwargs):
		
		register_form = RegisterForm(request.POST)
		if register_form.is_valid():
			try:
				username = register_form.cleaned_data['username']
				firstname = register_form.cleaned_data['firstname']
				lastname = register_form.cleaned_data['lastname']
				password = register_form.cleaned_data['password']
				password2 = register_form.cleaned_data['password2']
				phone = register_form.cleaned_data['phone']
				if (password == password2):
					user = User.objects.create_user(
					username=username,
					password=password)
					user.first_name, user.last_name = firstname, lastname
					user.save()
					profile = Profile(user=user, phone=phone )
					profile.save()
					messages.success(request, "Hello "+username+", you are registered successfully!")
					if user:
						login(request, user)
						return redirect("cv-admin")
				else:
					register_form = RegisterForm()
			except Exception as e:
				messages.error(request, str(e))
		register_form = RegisterForm()
		return render(request, self.template_name, locals())

@login_required(login_url='/login/')
def update(request, country_id):
	country = Country.objects.get(id=country_id)

	form = CountryForm(request.POST,  instance=country)
	if(request.method == 'POST'):
		if(form.is_valid()):
			form.save()
			return redirect('admin')
	form = CountryForm(instance=country)
	return render(request, "forms.html", locals())

def about(request):
	form = ConversionForm(request.POST)
	return render(request, 'about.html', locals())

def contact(request):
	form = ConversionForm(request.POST)
	form2 = ContactForm(request.POST)
	if(request.method == 'POST'):
		if 'send' in request.POST:
			if(form2.is_valid()):
				subject = form2.cleaned_data['subject']
				message = form2.cleaned_data['message']
				from_ = form2.cleaned_data['from_']
				to_ = 'cconverter@gmail.com'
				send_mail(
				    subject,
				    message,
				    from_,
				    [to_,],
				    fail_silently=False,
				)

	return render(request, 'contact.html', locals())

currencyConverter/templates/about.html
{% extends 'index.html' %}
{% load static %}
{% block titre %}<title>About | Currency Converter</title>{% endblock %}
	
	{% block banner %}
	<!-- Page top Section end -->
	<section class="page-top-section set-bg" data-setbg=" {% static 'img/page-top-bg/1.jpg' %} ">
		<div class="container">
			<h2>About us</h2>
			<nav class="site-breadcrumb">
				<a class="sb-item" href="#">Home</a>
				<span class="sb-item active">About us</span>
			</nav>
		</div>
	</section>
	<!-- Page top Section end -->
	{% endblock banner %}

	{% block content %}
	<!-- About Section end -->
	<section class="about-section spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<div class="about-text">
						<h2>A team to help you</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tem por incididunt ut labore et dolore mag na aliqua.  Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse potenti. Ut gravida mattis magna, non varius lorem sodales nec. In libero orci, ornare non nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tem por incididunt ut labore et dolore mag na aliqua.  Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse potenti. Ut gravida mattis magna, non varius lorem sodales nec. In libero orci, ornare non nisl.</p>
						<a href="#" class="site-btn mb-2">Find out more</a>
					</div>
				</div>
				<div class="col-lg-5">
					

					<form class="hero-form " method="post" enctype="multipart/form-data" action="." id="form">

								{% csrf_token %}
		                      	{% for field in form %}
		                      		<div class="form-group">
		                      		<label for="to" class="text-white">{{ field.label }}</label>
		                      		{{ field }}
								 </div>
		                      	{% endfor %}

								<div class="alert alert-info show" role="alert">
								  <strong  >Amount :  <span id="input"></span></strong><br>
								  <strong>Taux de transfert : <span id="taux" >{{ form.trans_percent.trans_percent }}</span> % </strong> <br>
								  <strong class="badge badge-success badge-customized">Output :  <span id="demo" ></span></strong><br> 
								</div>
					</form>
				</div>
			</div>
		</div>
	</section>
	<!-- About Section end -->


{% endblock content %}
	
{%  block why_us %}
{% endblock %}

{% block find_more %}
{% endblock %}

currencyConverter/templates/admin.html
{% extends 'index.html' %}
{% load static %}
{% block titre %}<title>Admin | Currency Converter</title>{% endblock %}

{% block banner %}
    <!-- Page top Section end -->
    <section class="page-top-section set-bg" data-setbg="{% static 'img/page-top-bg/4.jpg' %} ">
        <div class="container">
            <h2>Admin</h2>
            <nav class="site-breadcrumb">
                <a class="sb-item" href="#">Home</a>
                <span class="sb-item active">Admin</span>
            </nav>
        </div>
    </section>
    <!-- Page top Section end -->

{% endblock banner %}

{% block content %}

<section class="admin-section spad">

	    <div class="container">
	      <div class="row justify-content-center">
	        <div class="col-md-7 heading-section ftco-animate text-center">
	          <div class="card-body m-auto">
	              <form method="post" action=".">
	              	{% csrf_token %}
	              	<button type="submit" name="addCurrency" class="btn btn-outline-success">
                            Set Occurency
                    </button>
	              </form>
	          </div>
	        </div>
	      </div>
	    </div>

        <div class="container">
                <div class="table-responsive">
                  <h2 class="sub-header ">List Currency</h2>
                    <table class="table table-striped table-hover">
                      <thead>
                      	<tr>
                            <th >
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input checkAll">
                                    <label class="form-check-label">Id</label>
                                </div>
                            </th>
                            <th>Name</th>
                            <th>Currency</th>
                            <th>USD Value</th>
                            <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for country in countries %}
        	                <tr>
        	                    <td class="col-md-1">
        	                        <div class="form-check">
        	                            <input type="checkbox" class="form-check-input">
        	                            <label class="form-check-label">{{ country.id }}</label>
        	                        </div>
        	                    </td>
        	                    <td >{{ country.name }}</td>
        	                    <td >{{ country.currency }}</td>
        	                    <td >{{ country.usd_value }}</td>
        	                    <td >
        	                        <a type="button" href="{% url 'update' country.id %}" class="btn btn-primary btn-sm">Update</a>
        	                    </td>
        	                </tr>
        	               {% endfor %} 
                      </tbody>
                    </table>
                  
                </div>
        </div>
          
    	<div class="section " >
    	    <div class="container">
    	      <div class="row justify-content-center">
    	        <div class="col-md-7 heading-section ftco-animate text-center">
    	          <div class="card-body m-auto">
    	              <form method="post" action=".">
    	              	{% csrf_token %}
                            <button type="submit" name="addCurrency" class="btn btn-outline-success">
                                Set Occurency
                            </button>
    	              </form>
    	          </div>
    	        </div>
    	      </div>
    	    </div>
        </div>

</section>

{% endblock content %}

{%  block why_us %}
{% endblock %}

{% block find_more %}
{% endblock %}

currencyConverter/templates/contact.html
{% extends 'index.html' %}
{% load static %}
{% block titre %}<title>About | Currency Converter</title>{% endblock %}

{% block banner %}
	<!-- Page top Section end -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/page-top-bg/4.jpg' %} ">
		<div class="container">
			<h2>Contact</h2>
			<nav class="site-breadcrumb">
				<a class="sb-item" href="#">Home</a>
				<span class="sb-item active">Contact</span>
			</nav>
		</div>
	</section>
	<!-- Page top Section end -->
	

{% endblock banner %}
	{% block content %}
	<!-- Contact Section end -->
	<section class="contact-section spad"  data-setbg=" {% static 'img/score-bg.jpg' %} ">
		<div class="container">
			<div class="row">
				<div class="col-lg-4">
					<div class="contact-text">
						<h2>Get in touch</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tem por incididunt ut labore et dolore mag na aliqua.  Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hime-naeos. Suspendisse potenti. </p>
						<ul>
							<li><i class="flaticon-032-placeholder"></i>1525  Loans Lane, Los Angeles, CA</li>
							<li><i class="flaticon-029-telephone-1"></i>+1 (603)535-4592</li>
							<li><i class="flaticon-025-arroba"></i>hello@youremail.com</li>
							<li><i class="flaticon-038-wall-clock"></i>Everyday: 06:00 -22:00</li>
						</ul>
						<div class="social-links">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-instagram"></i></a>
							<a href="#"><i class="fa fa-linkedin"></i></a>
							<a href="#"><i class="fa fa-pinterest"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-youtube-play"></i></a>
						</div>
					</div>
				</div>
				<div class="col-lg-8">
					<form class="contact-form">
						<div class="row">
							<div class="col-md-6">
								<input type="text" placeholder="Your Name">
							</div>
							<div class="col-md-6">
								<input type="text" placeholder="Your E-mail">
							</div>
							<div class="col-md-12">
								<input type="text" placeholder="Subject">
								<textarea placeholder="Your Message"></textarea>
								<button class="site-btn">send message</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
	<!-- Contact Section end -->
{% endblock content %}

{%  block why_us %}
{% endblock %}

{% block find_more %}
{% endblock %}

currencyConverter/templates/forms.html
{% extends 'index.html' %}
{% load static %}

{% block banner %}
<!-- Page top Section end -->
    <section class="page-top-section set-bg" data-setbg=" {% static 'img/page-top-bg/1.jpg' %} ">
        <div class="container">
            <h2>Forms</h2>
            <nav class="site-breadcrumb">
                <a class="sb-item" href="#">Home</a>
                <span class="sb-item active">Forms</span>
            </nav>
        </div>
    </section>
    <!-- Page top Section end -->
{% endblock %}

{% block content %}
{% if form %}
    <section class="form-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-sm-12 offset-lg-3">
                    <div class="full">
                      <h4 class="card-title text-center">Set Curency</h4>
                        <form method="post" enctype="multipart/form-data" action="." class="form-signin">
                            <fieldset>
                              {% csrf_token %}
                               {{ form.as_p }}
                                <button class="btn btn-lg btn-outline-warning theme_color btn-block text-uppercase" type="submit">Set</button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endif %}
{% if form2 %}
    <section class="form-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-sm-12 offset-lg-3">
                    <div class="full">
                      <h4 class="card-title text-center">Set Curency</h4>
                        <form method="post" enctype="multipart/form-data" action="." class="form-signin">
                            <fieldset>
                              {% csrf_token %}
                               {{ form2.as_p }}
                                <button class="btn btn-lg btn-outline-warning theme_color btn-block text-uppercase" type="submit">Set</button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endif %}


{% if connexion_form %}
    <section class="form-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-sm-12 offset-lg-3">
                    <div class="full">
                       <h4 class="card-title text-center">Connexion</h4>
                        <form method="post" enctype="multipart/form-data" action="." class="form-signin">
                            <fieldset>
                              {% csrf_token %}
                              {{ connexion_form.as_p }}
                              <button class="btn btn-lg btn-outline-warning theme_color btn-block text-uppercase" type="submit">Connexion</button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endif %}


{% if register_form %}
    <section class="form-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-sm-12 offset-lg-3">
                    <div class="full">
                       <h4 class="card-title text-center">Register</h4>
                        <form  class="form-control" action="{% url 'register' %}"  method="post" enctype="multipart/form-data">
                          <fieldset>
                            {% csrf_token %}
                            {{ register_form.as_p }}
                            <button class="btn btn-lg btn-outline-warning theme_color btn-block text-uppercase" type="submit">Register</button>
                          </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endif %}

{% endblock %}

{%  block why_us %}
{% endblock %}

{% block find_more %}
{% endblock %}

currencyConverter/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
	{% block titre %}<title>Instant Transfer | Quick , Simple & Economic</title>{% endblock %}
	<meta charset="UTF-8">
	<meta name="description" content="loans HTML Template">
	<meta name="keywords" content="loans, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href=" {% static 'img/favicon.ico' %}" rel="shortcut icon"/>

	<!-- Google font 
	<link href=" {% static '' %} https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&display=swap" rel="stylesheet">-->
 
	<!-- Stylesheets -->
	<link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %} "/>
	<link rel="stylesheet" href=" {% static 'css/font-awesome.min.css' %} "/>
	<link rel="stylesheet" href=" {% static 'css/owl.carousel.min.css' %} "/>
	<link rel="stylesheet" href=" {% static 'css/flaticon.css' %} "/>
	<link rel="stylesheet" href=" {% static 'css/slicknav.min.css' %} "/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href=" {% static 'css/style.css' %} "/>


	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	{% block header %}

	<!-- Header Section -->
	
	<header class="header-section">
		<a href="index.html" class="site-logo">
			<img src=" {% static 'img/logo--4.png' %} " alt="">
		</a>
		<nav class="header-nav">
			<ul class="main-menu">
				<li><a href="{% url 'home' %}" class="active">Home</a></li>
				<li><a href="{% url 'contact' %}">Contact</a></li>
				<li><a href="{% url 'about' %}">About Us</a></li>
			</ul>
			<div class="header-right">
				<a href="#" class="hr-btn"><i class="flaticon-029-telephone-1"></i>Call us now! </a>
				<div class="hr-btn hr-btn-2">+257 61 460 068</div>
			</div>
		</nav>
	</header>
	<!-- Header Section end -->

	{% endblock header %}

	{% block banner %}
		
	{% endblock banner %}

	{% block content %}

	<!-- Hero Section end -->
	<section class="hero-section" id="tarrif">
		<div class="container">
			<div class="row">
				{% block aside %}
					
				<div class="col-lg-6">
					<div class="hs-text">
						<h2><strong><i class="fa fa-bell"></i>Instant Transfer</strong></h2>
						<p>
							Transferring money from one country to another has never been easy. High cost transfer fees, long waiting period. Receive and Send money easily and quicky with Instant Transfer.
						</p>

						<a href="#" class="site-btn sb-dark-opac sb-big"><i class="fa fa-angle-double-right"></i> Find out More</a>

					</div>
				</div>
				{% endblock aside %}

				{% block convert %}
				
				<div class="col-lg-6">

					<form class="hero-form " method="post" enctype="multipart/form-data" action="." id="form">

						{% csrf_token %}
                      	{% for field in form %}
                      		<div class="form-group">
                      		<label for="to" class="text-white">{{ field.label }}</label>
                      		{{ field }}
						 </div>
                      	{% endfor %}
                      	

						<div class="alert alert-info show" role="alert">
						  <strong  >Amount :  <span id="input"></span></strong><br>
						  <strong>Taux de transfert : <span id="taux" >{{ form.trans_percent.trans_percent }}</span> % </strong> <br>
						  <strong class="badge badge-success badge-customized">Output :  <span id="demo" ></span></strong><br> 
						</div>
					</form>
				</div>

				{% endblock convert %}
			</div>
		</div>
		<div class="hero-slider owl-carousel">
			<div class="hs-item set-bg" data-setbg=" {% static 'img/bg/bg-1.jpg' %} "></div>
		</div>
	</section>
	<!-- Hero Section end -->

	{% endblock content %}

	{% block why_us %}

	<!-- Why Section end -->
	<section class="why-section spad">
		<div class="container">
			<div class="text-center mb-5 pb-4">
				<h2>Why Choose us?</h2>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="icon-box-item">
						<div class="ib-icon">
							<i class="flaticon-012-24-hours"></i>
						</div>
						<div class="ib-text">
							<h5>Instant Transfer</h5>
							<p>Lorem ipsum dolor sit amet, consecte-tur adipiscing elit, sed do eiusmod tem por incididunt ut labore et dolore mag na aliqua. </p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="icon-box-item">
						<div class="ib-icon">
							<i class="flaticon-036-customer-service"></i>
						</div>
						<div class="ib-text">
							<h5>low cost transfer fees</h5>
							<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per incep-tos himenaeos. Suspendisse potenti. Ut gravida mattis.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="icon-box-item">
						<div class="ib-icon">
							<i class="flaticon-039-info"></i>
						</div>
						<div class="ib-text">
							<h5>Available in many countries</h5>
							<p>Conubia nostra, per inceptos himenae os. Suspendisse potenti. Ut gravida mattis magna, non varius lorem sodales nec. In libero orci.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="text-center pt-3">
				<a href="#tarrif" class="site-btn sb-big">Know our tarrif</a>
			</div>
		</div>
	</section>
	<!-- Why Section end -->
{% endblock why_us %}

{% block find_more %}
	<!-- CTA Section end -->
	<section class="cta-section set-bg" data-setbg=" {% static 'img/cta-bg.jpg' %} ">
		<div class="container">
			<h2>Want to know more about <strong>Instant Transfer</strong>?</h2>
			<h5>fint out more informations about our services</h5>
			<a href="#" class="site-btn sb-dark sb-big">Find out More</a>
		</div>
	</section>
	<!-- CTA Section end -->
{% endblock find_more %}

	<!-- Footer Section -->
	<footer class="footer-section">
		<div class="container">
			<div class="text-center">
				
			<span class="text-white text-center text-footer">
			Copyright &copy;<script>document.write(new Date().getFullYear());</script> | <strong ><span class="text-danger">Instant</span> <span class="text-warning">Transfer</span> - Simple, Quick & Economic</strong>				
			</span>
			</div>
		</div>
	</footer>
	<!-- Footer Section end -->
	
	<!--====== Javascripts & Jquery ======-->
	<script src=" {% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src=" {% static 'js/bootstrap.min.js' %}"></script>
	<script src=" {% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src=" {% static 'js/owl.carousel.min.js' %}"></script>
	<script src=" {% static 'js/jquery-ui.min.js' %}"></script>
	<script src=" {% static 'js/main.js' %}"></script>

	<script type="text/javascript">
		jQuery(document).ready(function($) {
			var taux = parseFloat(document.getElementById('taux').innerHTML);
		  $("#id_amount").keyup(function (event) {
		    var from = parseFloat($("#id_country_from").val());
		    var to = parseFloat($("#id_country_to").val());
		    var x = parseFloat($("#id_amount").val());
		    var new_amount = parseFloat($(this).val())*from/to;
		    var computed_amount = new_amount + (new_amount*taux/100);
		    $("#demo").text(computed_amount.toFixed(2));
		    $("#input").text(x);
		  });
		});
    
</script>
	</body>
</html>